// data/snippets/testimonials/testimonials.vue
<template>
<main class="main">

    <div class="page-header">

      <h1>Testimonials</h1>

      <p>
        Beautiful modern testimonial cards designed with
        glassmorphism, premium hover animations, gradient glow
        effects, and elegant typography.
      </p>

    </div>

    <!-- Testimonials -->

    <div class="testimonial-grid">

      <!-- Card 1 -->

      <div class="component-card">

        <h3>Customer Testimonial</h3>

        <div class="testimonial-card">

          <div class="blur-glow"></div>

          <div class="quote-icon">❝</div>

          <div class="stars">
            <span>★</span>
            <span>★</span>
            <span>★</span>
            <span>★</span>
            <span>★</span>
          </div>

          <p>
            “UIverse helped us launch faster with polished
            UI components that were elegant, scalable,
            and incredibly easy to customize.”
          </p>

          <div class="testimonial-meta">

            <div class="avatar">
              <img
                src="https://i.pravatar.cc/100?img=5"
                alt=""
               srcset="https://i.pravatar.cc/40?img=5 40w, https://i.pravatar.cc/80?img=5 80w, https://i.pravatar.cc/150?img=5 150w, https://i.pravatar.cc/300?img=5 300w" sizes="(max-width: 768px) 96px, 160px" loading="lazy" decoding="async">
            </div>

            <div class="user-info">
              <strong>Maya Lee</strong>
              <span>Product Designer</span>
            </div>

          </div>

        </div>

        <div class="actions">
          <button class="action-btn view-btn" onclick="toggleCode('t1', this)"><i class="fa-solid fa-code"></i> View Code</button>
          <button class="action-btn copy-btn" onclick="copyCode('t1', this)"><i class="fa-solid fa-copy"></i> Copy</button>
        </div>

<pre id="t1" class="code-block">
&lt;div class="testimonial-card"&gt;
  Modern glowing testimonial card
&lt;/div&gt;
</pre>

      </div>

      <!-- Card 2 -->

      <div class="component-card">

        <h3>Quote Panel</h3>

        <div class="testimonial-card">

          <div class="blur-glow"></div>

          <div class="quote-icon">❝</div>

          <div class="stars">
            <span>★</span>
            <span>★</span>
            <span>★</span>
            <span>★</span>
            <span>★</span>
          </div>

          <p>
            “The component library is beginner friendly
            and made styling my app feel effortless,
            modern, and professional.”
          </p>

          <div class="testimonial-meta">

            <div class="avatar">
              <img
                src="https://i.pravatar.cc/100?img=12"
                alt=""
               srcset="https://i.pravatar.cc/40?img=12 40w, https://i.pravatar.cc/80?img=12 80w, https://i.pravatar.cc/150?img=12 150w, https://i.pravatar.cc/300?img=12 300w" sizes="(max-width: 768px) 96px, 160px" loading="lazy" decoding="async">
            </div>

            <div class="user-info">
              <strong>Alex Chen</strong>
              <span>Frontend Developer</span>
            </div>

          </div>

        </div>

        <div class="actions">
          <button class="action-btn view-btn" onclick="toggleCode('t2', this)"><i class="fa-solid fa-code"></i> View Code</button>
          <button class="action-btn copy-btn" onclick="copyCode('t2', this)"><i class="fa-solid fa-copy"></i> Copy</button>
        </div>

<pre id="t2" class="code-block">
&lt;div class="testimonial-card"&gt;
  Premium quote testimonial
&lt;/div&gt;
</pre>

      </div>

    </div>

  </main>
</template>

<script>
export default { name: 'Testimonials' }
</script>

// data/snippets/testimonials/testimonials.jsx
import React from 'react';

export default function testimonials(){
  return (
    <>
      <main className="main">
      
          <div className="page-header">
      
            <h1>Testimonials</h1>
      
            <p>
              Beautiful modern testimonial cards designed with
              glassmorphism, premium hover animations, gradient glow
              effects, and elegant typography.
            </p>
      
          </div>
      
          {/* Testimonials */}
      
          <div className="testimonial-grid">
      
            {/* Card 1 */}
      
            <div className="component-card">
      
              <h3>Customer Testimonial</h3>
      
              <div className="testimonial-card">
      
                <div className="blur-glow"></div>
      
                <div className="quote-icon">❝</div>
      
                <div className="stars">
                  <span>★</span>
                  <span>★</span>
                  <span>★</span>
                  <span>★</span>
                  <span>★</span>
                </div>
      
                <p>
                  “UIverse helped us launch faster with polished
                  UI components that were elegant, scalable,
                  and incredibly easy to customize.”
                </p>
      
                <div className="testimonial-meta">
      
                  <div className="avatar">
                    <img
                      src="https://i.pravatar.cc/100?img=5"
                      alt=""
                     srcset="https://i.pravatar.cc/40?img=5 40w, https://i.pravatar.cc/80?img=5 80w, https://i.pravatar.cc/150?img=5 150w, https://i.pravatar.cc/300?img=5 300w" sizes="(max-width: 768px) 96px, 160px" loading="lazy" decoding="async" />
                  </div>
      
                  <div className="user-info">
                    <strong>Maya Lee</strong>
                    <span>Product Designer</span>
                  </div>
      
                </div>
      
              </div>
      
              <div className="actions">
                <button className="action-btn view-btn" onclick="toggleCode('t1', this)"><i className="fa-solid fa-code"></i> View Code</button>
                <button className="action-btn copy-btn" onclick="copyCode('t1', this)"><i className="fa-solid fa-copy"></i> Copy</button>
              </div>
      
      <pre id="t1" className="code-block">
      &lt;div className="testimonial-card"&gt;
        Modern glowing testimonial card
      &lt;/div&gt;
      </pre>
      
            </div>
      
            {/* Card 2 */}
      
            <div className="component-card">
      
              <h3>Quote Panel</h3>
      
              <div className="testimonial-card">
      
                <div className="blur-glow"></div>
      
                <div className="quote-icon">❝</div>
      
                <div className="stars">
                  <span>★</span>
                  <span>★</span>
                  <span>★</span>
                  <span>★</span>
                  <span>★</span>
                </div>
      
                <p>
                  “The component library is beginner friendly
                  and made styling my app feel effortless,
                  modern, and professional.”
                </p>
      
                <div className="testimonial-meta">
      
                  <div className="avatar">
                    <img
                      src="https://i.pravatar.cc/100?img=12"
                      alt=""
                     srcset="https://i.pravatar.cc/40?img=12 40w, https://i.pravatar.cc/80?img=12 80w, https://i.pravatar.cc/150?img=12 150w, https://i.pravatar.cc/300?img=12 300w" sizes="(max-width: 768px) 96px, 160px" loading="lazy" decoding="async" />
                  </div>
      
                  <div className="user-info">
                    <strong>Alex Chen</strong>
                    <span>Frontend Developer</span>
                  </div>
      
                </div>
      
              </div>
      
              <div className="actions">
                <button className="action-btn view-btn" onclick="toggleCode('t2', this)"><i className="fa-solid fa-code"></i> View Code</button>
                <button className="action-btn copy-btn" onclick="copyCode('t2', this)"><i className="fa-solid fa-copy"></i> Copy</button>
              </div>
      
      <pre id="t2" className="code-block">
      &lt;div className="testimonial-card"&gt;
        Premium quote testimonial
      &lt;/div&gt;
      </pre>
      
            </div>
      
          </div>
      
        </main>
    </>
  );
}
